name: auto-merge

on:
  pull_request:
    branches: [master]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: auto merge
        # Custom action for auto merging already available on marketplace
        uses: pascalgn/automerge-action@v0.12.0
        with:
          args: '--trace'
        # Perform the auto merge action only when the PR is raised by the bot
        if: github.actor == 'rpbeukes-bot'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_PAT }}
          MERGE_METHOD: squash
          UPDATE_METHOD: 'rebase'
