name: bump-packages

on:
  pull_request:
    branches: [master] # wil become master

jobs:
  create-bump-PR:
    name: create-bump-PR
    runs-on: ubuntu-latest
    env:
      BUMP_BRANCH_NAME: bump-packages-test # will become bump-packages
      MASTER_BRANCH_NAME: auto-merge-test # wil become master
      GIT_COMMIT_MESSAGE: bump package versions to latest.
      PR_TITLE: TEST - bump all packages (rpbeukes-bot)
      IS_BUMP_NEEDED: false

    steps:
      # # share the variables with steps below
      # - name: set BUMP_BRANCH_NAME environment variable
      #   run: |
      #     echo "BUMP_BRANCH_NAME=bump-packages" >> $GITHUB_ENV

      - name: install npm-check-updates (ncu)
        run: sudo npm install -g npm-check-updates

      - uses: actions/checkout@v2
        name: checkout branch to raise a PR against
        with:
          ref: ${{ env.MASTER_BRANCH_NAME }}

      - name: update packages with npm-check-updates
        run: ncu --doctor --upgrade

      - name: set IS_BUMP_NEEDED to output of 'git status | grep "package.json"'
        run: echo "IS_BUMP_NEEDED=`git status | grep "package.json"`" >> $GITHUB_ENV

      - name: set IS_BUMP_NEEDED
        if: ${{contains(env.IS_BUMP_NEEDED, 'package.json')}}
        run: echo "IS_BUMP_NEEDED=true >> $GITHUB_ENV

      - name: create and checkout bump branch
        if: ${{env.IS_BUMP_NEEDED == 'true'}}
        run: git branch $BUMP_BRANCH_NAME && git checkout $BUMP_BRANCH_NAME

      - name: add package.json package-lock.json changes
        if: ${{env.IS_BUMP_NEEDED == 'true'}}
        run: |
          git add package.json package-lock.json

      - name: set 'rpbeukes-bot' as the git user
        if: ${{env.IS_BUMP_NEEDED == 'true'}}
        run: |
          git config --local user.email "ruancoder+bot@gmail.com"
          git config --local user.name "rpbeukes-bot"

      - name: add commit message
        if: ${{env.IS_BUMP_NEEDED == 'true'}}
        run: git commit -m "$GIT_COMMIT_MESSAGE"

      - name: push branch `$BUMP_BRANCH_NAME`
        run: git push --set-upstream origin $BUMP_BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_PAT }}

      - name: create PR 'bump all packages (rpbeukes-bot)'
        if: ${{env.IS_BUMP_NEEDED == 'true'}}
        run: |
          hub pull-request --base $MASTER_BRANCH_NAME -m "$PR_TITLE"
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_PAT }}
